dbt_practica:
  outputs:
    dev:
      dbname: mvenzor_db
      host: localhost
      pass: '5121'
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: mvenzor
  target: dev
predictive_maintenance:
  outputs:
    dev:
      dbname: mvenzor_db
      host: localhost
      pass: '5121'
      port: 5432
      schema: dev
      threads: 1
      type: postgres
      user: mvenzor
  target: dev
chicago_food_inspections:
  target: dev
  outputs:
    dev:
      type: postgres
      dbname: mvenzor_db
      user: mvenzor
      password: "5121"
      schema: public
      threads: 4
      host: 172.29.180.193
      port: 5432
